cn: host.docker.internal
reverse-proxy-uri: https://${cn}
issuer: ${reverse-proxy-uri}/auth/realms/labs

server:
  port: 8084
  ssl:
    enabled: true
    bundle: self-signed

spring:
  application:
    name: user-service$
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: ${issuer}
        registration:
          user-service:
            provider: sso
            authorization-grant-type: client_credentials
            client-id: user-service
            client-secret: secret
  ssl:
    bundle:
      pem:
        self-signed:
          keystore:
            certificate: classpath:${cn}.crt
            private-key: classpath:${cn}.key
          truststore:
            certificate: classpath:${cn}.crt
  web:
    error:
      include-message: always

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            authorities:
              - path: $.realm_access.roles
        resourceserver:
          permit-all:
            - /users/me
            - /actuator/health/readiness
            - /actuator/health/liveness
            - /actuator/prometheus
            - /v3/api-docs/**
            - /swagger-ui/**
      rest:
        client:
          keycloak-admin-api-client:
            base-url: ${reverse-proxy-uri}/auth
            ssl-bundle: self-signed
            authorization:
              oauth2:
                oauth2-registration-id: user-service
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: ${spring.application.name}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://host.docker.internal:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://host.docker.internal:4318/v1/logs
  otlp:
    metrics:
      export:
        url: http://host.docker.internal:4318/v1/metrics

logging:
  level:
    "[org.springframework]": INFO
---
spring:
  config:
    activate:
      on-profile: no-observability
management:
  endpoint:
    health:
      probes:
        enabled: false
  health:
    livenessstate:
      enabled: false
    readinessstate:
      enabled: false
  logging:
    export:
      otlp:
        enabled: false
  tracing:
    export:
      enabled: false
  opentelemetry:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false