name: bdp-labs

volumes:
  accounts_data:
    driver: local
  card_payments_data:
    driver: local
  customers_data:
    driver: local

secrets:
  rest_api_db_password:
    file: ./secrets/rest-api/postgres_password.txt

services:
  accounts_db:
    container_name: bdp-labs.accounts-db
    image: postgres:18
    hostname: ${CN}
    restart: unless-stopped
    ports:
      - "${ACCOUNTS_DB_PORT}:5432"
    secrets:
      - rest_api_db_password
    environment:
      POSTGRES_DB: accounts
      POSTGRES_USER: rest-api
      POSTGRES_PASSWORD_FILE: /run/secrets/rest_api_db_password
      TZ: "Pacific/Tahiti"
    volumes:
      - accounts_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bdp-labs -U rest-api -p 5432"]
      interval: 3s
      timeout: 60s
      retries: 20
    extra_hosts:
      - host.docker.internal:host-gateway

  card_payments_db:
    container_name: bdp-labs.card-payments-db
    image: postgres:18
    hostname: ${CN}
    restart: unless-stopped
    ports:
      - "${CARD_PAYMENTS_DB_PORT}:5432"
    secrets:
      - rest_api_db_password
    environment:
      POSTGRES_DB: card_payments
      POSTGRES_USER: rest-api
      POSTGRES_PASSWORD_FILE: /run/secrets/rest_api_db_password
      TZ: "Pacific/Tahiti"
    volumes:
      - card_payments_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bdp-labs -U rest-api -p 5432"]
      interval: 3s
      timeout: 60s
      retries: 20
    extra_hosts:
      - host.docker.internal:host-gateway

  customers_db:
    container_name: bdp-labs.customers-db
    image: postgres:18
    hostname: ${CN}
    restart: unless-stopped
    ports:
      - "${CUSTOMERS_DB_PORT}:5432"
    secrets:
      - rest_api_db_password
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: rest-api
      POSTGRES_PASSWORD_FILE: /run/secrets/rest_api_db_password
      TZ: "Pacific/Tahiti"
    volumes:
      - customers_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bdp-labs -U rest-api -p 5432"]
      interval: 3s
      timeout: 60s
      retries: 20
    extra_hosts:
      - host.docker.internal:host-gateway