name: bdp-labs

volumes:
  rest_api_data:
    driver: local

secrets:
  rest_api_db_password:
    file: ./secrets/rest-api/postgres_password.txt

services:
  rest_api_db:
    container_name: bdp-labs.rest-api-db
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    secrets:
      - rest_api_db_password
    environment:
      TZ: "Pacific/Tahiti"
      POSTGRES_USER: rest-api
      POSTGRES_PASSWORD_FILE: /run/secrets/rest_api_db_password
    volumes:
      - rest_api_data:/var/lib/postgresql
    entrypoint: [ "/bin/bash", "-c","
      docker-entrypoint.sh postgres &
      rm -f /initialised.txt || true &&
      until pg_isready -U postgres; do sleep 3; done &&
      psql -U rest-api -d postgres -c 'CREATE DATABASE accounts;' || true &&
      psql -U rest-api -d postgres -c 'CREATE DATABASE card_payments;' || true &&
      psql -U rest-api -d postgres -c 'CREATE DATABASE customers;' || true &&
      echo done > /initialised.txt &&
      wait"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d bdp-labs -U $(cat /run/secrets/rest_api_db_user) -p 5432"]
      interval: 3s
      timeout: 60s
      retries: 20
    extra_hosts:
      - host.docker.internal:host-gateway