name: bdp-labs

volumes:
  keycloak:
    driver: local

secrets:
  kc_db_user:
    file: ./secrets/keycloak/postgres_user.txt
  kc_db_password:
    file: ./secrets/keycloak/postgres_password.txt

services:
  keycloak-db:
    container_name: bdp-labs.keycloak-db
    image: ${KC_DB_IMAGE}
    command:
      - -p ${KC_DB_PORT}
    restart: unless-stopped
    ports:
      - "${KC_DB_PORT}:${KC_DB_PORT}"
    secrets:
      - kc_db_user
      - kc_db_password
    environment:
      TZ: "Pacific/Tahiti"
      POSTGRES_USER_FILE: /run/secrets/kc_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/kc_db_password
      POSTGRES_DB: ${KC_DB_NAME}
    volumes:
      -  keycloak:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${KC_DB_NAME} -U ${KC_DB_USERNAME} -p ${KC_DB_PORT}"]
      interval: 3s
      timeout: 60s
      retries: 20

  keycloak-server:
    container_name: bdp-labs.keycloak-server
    image: bdp-labs.c4-soft.com/keycloak:${KC_VERSION}
    command:
      - start
      - --db-username=${KC_DB_USERNAME}
      - --db-password=${KC_DB_PASSWORD}
      - --https-certificate-file=/opt/keycloak/certs/${CN}.crt
      - --https-certificate-key-file=/opt/keycloak/certs/${CN}.key
      - --bootstrap-admin-username=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - --bootstrap-admin-password=${KC_BOOTSTRAP_ADMIN_PASSWORD}
      - --import-realm
      - --optimized
    restart: unless-stopped
    ports:
      - ${KC_HTTPS_PORT}:${KC_HTTPS_PORT}
      - 9000:9000
    volumes:
      - ./keycloak/import/:/opt/keycloak/data/import/:ro
      - ./keycloak/providers/:/opt/keycloak/providers/:ro
      - ./keycloak/HealthCheck.java:/tmp/HealthCheck.java:ro
    environment:
      KC_PROXY_HEADERS: xforwarded
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      keycloak-db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'java /tmp/HealthCheck.java https://localhost:9000/auth/health/ready']
      interval: 5s
      timeout: 5s
      retries: 10