cn: host.docker.internal
reverse-proxy-uri: https://${cn}
issuer: ${reverse-proxy-uri}/auth/realms/labs
card-service-client-id: card-service
card-service-client-secret: secret

server:
  port: 8082
  ssl:
    enabled: true
    bundle: self-signed

spring:
  application:
    name: card-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    active:
      - postgresql
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: ${issuer}
        registration:
          card-service:
            provider: sso
            authorization-grant-type: client_credentials
            client-id: ${card-service-client-id}
            client-secret: ${card-service-client-secret}
            
  ssl:
    bundle:
      pem:
        self-signed:
          keystore:
            certificate: classpath:${cn}.crt
            private-key: classpath:${cn}.key
          truststore:
            certificate: classpath:${cn}.crt
  web:
    error:
      include-message: always

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            authorities:
              - path: $.realm_access.roles
        resourceserver:
          permit-all:
            - /actuator/health/readiness
            - /actuator/health/liveness
            - /actuator/prometheus
            - /v3/api-docs/**
            - /swagger-ui/**
      rest:
        client:
          account-service-client:
            base-url: ${reverse-proxy-uri}/gateway/m2m
            ssl-bundle: self-signed
            headers:
              Accept: application/problem+json
            authorization:
              oauth2:
                oauth2-registration-id: card-service

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: ${spring.application.name}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://host.docker.internal:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://host.docker.internal:4318/v1/logs
  otlp:
    metrics:
      export:
        url: http://host.docker.internal:4318/v1/metrics

logging:
  level:
    "[org.springframework]": INFO

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:card_payments
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://host.docker.internal:2634/card_payments
    username: rest-api
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect