cn: host.docker.internal
reverse-proxy-uri: https://${cn}
issuer: ${reverse-proxy-uri}/auth/realms/labs
customer-service-client-id: customer-service
customer-service-client-secret: secret

keycloak-admin-api:
  base-uri: ${reverse-proxy-uri}/auth
  realm-name: labs

server:
  port: 8083
  shutdown: immediate
  ssl:
    enabled: true
    bundle: self-signed

spring:
  application:
    name: customer-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  profiles:
    active:
      - postgresql
  security:
    oauth2:
      client:
        provider:
          sso:
            issuer-uri: ${issuer}
        registration:
          customer-service:
            provider: sso
            authorization-grant-type: client_credentials
            client-id: ${customer-service-client-id}
            client-secret: ${customer-service-client-secret}
  ssl:
    bundle:
      pem:
        self-signed:
          keystore:
            certificate: classpath:${cn}.crt
            private-key: classpath:${cn}.key
          truststore:
            certificate: classpath:${cn}.crt
  web:
    error:
      include-message: always

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: ${issuer}
            authorities:
              - path: $.realm_access.roles
        resourceserver:
          permit-all:
            - /actuator/health/readiness
            - /actuator/health/liveness
            - /actuator/prometheus
            - /v3/api-docs/**
            - /swagger-ui/**
      rest:
        client:
          keycloak-admin-api-client:
            base-url: ${reverse-proxy-uri}/auth
            ssl-bundle: self-signed
            headers:
              Accept: application/problem+json
            authorization:
              oauth2:
                oauth2-registration-id: customer-service
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: ${spring.application.name}
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://host.docker.internal:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://host.docker.internal:4318/v1/logs
  otlp:
    metrics:
      export:
        url: http://host.docker.internal:4318/v1/metrics

logging:
  level:
    "[org.springframework]": INFO

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:customers
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
---
spring:
  config:
    activate:
      on-profile: postgresql
  datasource:
    url: jdbc:postgresql://host.docker.internal:2635/customers
    username: rest-api
    password: secret
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
---
spring:
  config:
    activate:
      on-profile: no-observability
management:
  endpoint:
    health:
      probes:
        enabled: false
  health:
    livenessstate:
      enabled: false
    readinessstate:
      enabled: false
  logging:
    export:
      otlp:
        enabled: false
  tracing:
    export:
      enabled: false
  opentelemetry:
    enabled: false
  otlp:
    metrics:
      export:
        enabled: false